# Generated by Django 4.2.15 on 2024-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('date_of_last_update', models.DateField(auto_now=True)),
                ('nick', models.CharField(max_length=255)),
                ('password', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('main_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
