# Generated by Django 4.2.15 on 2024-08-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_natural_person_staff'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
            preserve_default=False,
        ),
    ]
